library: Add Grid entry
sonnyp/Workbench pull request #233
Opened 2023-03-15 14:25 UTC by bazylevnik0

2023-03-16 21:27 UTC, sonnyp requested changes
Good start!

We try to make Library entries nice to look at and interactive (but still comprehensible).

What about a (very) simple tic tac toe with a 3x3 grid? Since it will require some JavaScript it's also a good opportunity to showcase the APIs to work with grid.

Don't worry too much about style, we can iterate later.

2023-03-17 07:45 UTC, bazylevnik0 commented on src/about.js
> +    "bazylevnik0 https://github.com/AkshayWarrier",
Yep :)

2023-03-21 17:43 UTC, sonnyp reviewed
I should have been more explicit. With tic tac toe - I meant as a (very simple) game you can play against the computer.

Similar to https://playtictactoe.org/

For the UI please make each cell square.
You can use `circle-outline-thick-symbolic` and `cross-large-symbolic` icons

If you make it look like a tic tac toe - we don't need to explain :)

2023-03-21 17:43 UTC, sonnyp commented on src/Library/demos/Grid/main.blp
> +  description: _("Arrange widgets in rows and columns.\n\n*Tic Tac Toe: just click to the '#' for 'x' and click again for 'o':");
```suggestion
  description: _("Arrange widgets in rows and columns.");
```

hopefully we won't need to explain the UI :)

2023-03-26 15:52 UTC, sonnyp reviewed
Cool.

Regarding the design:

1. No need for edit mode
2. Have one of the cell by default O or X so that it's clear for the user what they're looking at
3. Make the cells square
4. Only show big  O / X, no background

The icons should be visible and light and dark modes - if you stick to the default color that should work fine

2023-03-26 15:52 UTC, sonnyp commented on src/Library/demos/Grid/main.json
> +    "preview"
Should be enough to see quickly what Grid is about:

```suggestion
    "ui",
    "preview"
```

2023-04-01 20:49 UTC, sonnyp requested changes
Looks great now!

Just a few more changes and this is ready to go.

Try to make sure the code is always easy to reason about.

2023-04-01 20:49 UTC, sonnyp commented on src/Library/demos/Grid/main.css
> +}
the default `hover` is fine, you can remove this

```suggestion
```

2023-04-01 20:49 UTC, sonnyp commented on src/Library/demos/Grid/main.css
> +#button22 {
in CSS, you should use a class to to make styling reusable between different elements

```suggestion
.cell {
```

You can apply the class to each button using the `styles ['cell']` syntax

And remove `name` on all `button`

2023-04-01 20:49 UTC, sonnyp commented on src/Library/demos/Grid/main.json
> +  "description": "Allow people to perform using a grids",
```suggestion
  "description": "Arrange widgets in rows and columns.",
```

2023-04-01 20:49 UTC, sonnyp commented on src/Library/demos/Grid/main.js
> +  ) {
an early return would make the function easier to read and reduce one level of indentation

something like

```suggestion
  if (clicked.icon_name) return;
```

2023-04-01 20:49 UTC, sonnyp commented on src/Library/demos/Grid/main.js
> +  let clicked = button.get_child();
let's name it after what it is for clarity

```suggestion
  let image = button.get_child();
```

2023-04-01 20:49 UTC, sonnyp commented on src/Library/demos/Grid/main.js
> +    let pc_is_thinking_col;
these don't need to be scope outside the `while`

2023-04-01 20:49 UTC, sonnyp commented on src/Library/demos/Grid/main.js
> +      ) {
ditto

2023-04-01 20:49 UTC, sonnyp commented on src/Library/demos/Grid/main.blp
> +        Image image00{
```suggestion
        Image {
```

you can remove all ids on image, they're not used

2023-04-02 13:33 UTC, sonnyp approved these changes
The point if early return is that you don't need the `else` :)

I fixed it in https://github.com/sonnyp/Workbench/pull/233/commits/810fadfe75bfd6fc5de85e4c7386b465d7c73d49

Thanks for the contribution!

2023-04-02 13:33 UTC, merged