library: Add Font Dialog Entry
sonnyp/Workbench pull request #244
Opened 2023-03-22 11:19 UTC by SoNiC-HeRE

Adds Font Dialog Entry
Issue #69

2023-03-22 18:55 UTC, sonnyp requested changes
The entry doesn't appear in the library

> (re.sonny.Workbench.Devel:4): re.sonny.Workbench.Devel-WARNING **: 19:53:44.496: The demo name "Font Chooser" does not match the folder name "Font Dialog" and will be ignored.

2023-03-22 18:55 UTC, sonnyp commented on src/Library/demos/Font Dialog/main.js
> +const dialog_custom = new Gtk.FontChooserDialog({
this is the deprecated API

2023-03-22 21:42 UTC, SoNiC-HeRE commented
I'll fix it

2023-03-22 21:44 UTC, SoNiC-HeRE commented on src/Library/demos/Font Dialog/main.js
> +const dialog_custom = new Gtk.FontChooserDialog({
okay, I'll update this with the new one

2023-05-28 09:32 UTC, sonnyp commented
@SoNiC-HeRE please make sure to update this to use `FontDialog` instead of the deprecated `FontChooserDialog`

2023-06-01 04:28 UTC, SoNiC-HeRE commented
I'm unsure why I'm getting an empty object or undefined value when i'm trying to get the value from Gtk.FontDialog. It seeems to work fine with Gtk.FontDialogButton but not with a custom button. I'm using this for reference: https://docs.gtk.org/gtk4/class.FontDialog.html

2023-06-02 20:29 UTC, SoNiC-HeRE commented
The demo seems to be working now , had to fix an error. It is ready for review now

2023-06-02 20:34 UTC, SoNiC-HeRE commented
The demo seems to be working now , had to fix an error. It is ready for review now

2023-06-03 11:49 UTC, sonnyp approved these changes
:+1: 

made some minor changes https://github.com/sonnyp/Workbench/pull/244/commits/23210020aff341dea2dab031390a294cd0153148

2023-06-03 11:50 UTC, merged