library: Status Page Demo
sonnyp/Workbench pull request #252
Opened 2023-03-27 14:31 UTC by Datagirlcmr

Add the files for  a status page
implement a default statuspage

2023-03-27 21:24 UTC, andyholmes commented on src/Library/demos/Scrollbar/main.blp
This second demo should be moved to a separate branch.

Generally in FOSS communities, and especially GNOME, we follow a "feature branch" workflow. That usually looks something like this:

```sh
# Keep separate remotes with your fork as "origin" and the main repository as "upstream"
git clone git@github.com:Datagirlcmr/Workbench-gnome.git && cd Workbench
git remote add upstream git@github.com:sonnyp/Workbench.git

# Switch the main branch and pull the latest upstream code
git switch main
git pull upstream main

# Switch to a new branch for the feature
git switch -c datagirlcmr/scrollbar-demo
# Push the branch to your remote
git push -u origin datagirlcmr/scrollbar-demo
```

To migrate your current work, you can:

```sh
# Assuming the remotes have been setup as above
git switch main && git pull upstream main
git switch -c datagirlcmr/scrollbar-demo
# This is the actual commit hash from your Scrollbar Demo
git cherry-pick dc70900
```

2023-03-27 21:29 UTC, andyholmes requested changes
It looks like your demos aren't quite ready to go. 

Please mark your pull requests as "Draft" until they are ready to be reviewed, and be sure to give them a test run in Workbench.

2023-03-27 21:29 UTC, andyholmes commented on src/Library/demos/Status Page/main.blp
This file is missing all of the elements referred to in `Status Page/main.js`.

2023-03-27 21:29 UTC, andyholmes commented on src/Library/demos/Status Page/main.js
> +button.connect("clicked", () => {
Because this isn't in the BluePrint UI file, this causes an error preventing the demo from loading.

2023-03-29 02:56 UTC, Datagirlcmr commented
We can archive this pull request, as I have opened a different one with changes

2023-03-29 16:12 UTC, closed without merging