Adds Adw.Clamp Demo
sonnyp/Workbench pull request #301
Opened 2023-06-04 06:26 UTC by SoNiC-HeRE

Closes #287 

Implemented Adw.Clamp demo following the description that was discussed. Added some more functionality to enhance UI. Looking for an early review.

2023-06-04 23:29 UTC, sonnyp requested changes
It doesn't build.
The formatting is off.
The strings should use `_()`

Please test and review your work before submitting.

2023-06-04 23:29 UTC, sonnyp commented on src/Library/demos/Clamp/main.blp
> +      uri: "https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.Clamp.html";
Links should be to adw 1.3 docs

2023-06-06 09:30 UTC, SoNiC-HeRE commented
Made the following Changes:
1) Fixed the build error
2) Replaced Gtk.TextView with Gtk.Label
3) Refined Code

2023-06-10 21:41 UTC, andyholmes commented
If this is one ready for re-review, please remember to hit that button again :slightly_smiling_face: We don't want to make you wait, or start re-reviewing before you're ready.

2023-08-13 14:32 UTC, sonnyp approved these changes
I wanted to do something more complicated but I think this is a good entry anyway and it's easy to go from it to the documentation.

2023-08-13 14:32 UTC, merged