Adds Adw.AboutWindow Demo
sonnyp/Workbench pull request #305
Opened 2023-06-06 10:33 UTC by SoNiC-HeRE

Closes #283

2023-06-06 10:34 UTC, SoNiC-HeRE commented
Looking for an early review

2023-06-06 10:38 UTC, SoNiC-HeRE commented
Implemented Adw.About Window demo , Looking for an early review

2023-06-07 04:13 UTC, SoNiC-HeRE commented
Changed the design and code to implement something similar to :
![image](https://github.com/sonnyp/Workbench/assets/96797205/d5891dcc-ee26-4a8d-8ab8-c91bb0c06898)

2023-06-07 04:22 UTC, SoNiC-HeRE commented
Changed the design and code to implement something similar to :
Was'nt sure about the credit section so thought of adding mine 

![image](https://github.com/sonnyp/Workbench/assets/96797205/d5891dcc-ee26-4a8d-8ab8-c91bb0c06898)

2023-06-12 03:56 UTC, andyholmes requested changes
This looks great, nice and simple.

One thing worth demoing is `Adw.AboutWindow.add_acknowledgement_section()`, since that gets used for donation pages. Then LGTM!

2023-06-13 23:30 UTC, andyholmes approved these changes
Nice one!

2023-06-13 23:38 UTC, merged