library: Add User Info Entry
sonnyp/Workbench pull request #353
Opened 2023-06-19 17:19 UTC by SoNiC-HeRE

Closes #346

2023-06-19 17:26 UTC, SoNiC-HeRE commented
## Overview:
- Kept the design minimalistic
- Used promisified methods
- Commented parts of the code for better understanding

Looking for an early review

2023-06-19 19:47 UTC, sonnyp requested changes
Looks great

I think we should call the demo "Account" though, it's a bit clearer

2023-06-19 19:47 UTC, sonnyp commented on src/Library/demos/User Info/main.blp
> +  title: "User Info";
```suggestion
  title: _("User Info");
```

2023-06-19 19:47 UTC, sonnyp commented on src/Library/demos/User Info/main.blp
> +  description: _("Request user information");
```suggestion
  description: _("Request information about the user");
```

2023-06-19 19:47 UTC, sonnyp commented on src/Library/demos/User Info/main.blp
> +      label: _("What best describes your request?");
```suggestion
      label: _("What is the reason for the request?");
```

2023-06-19 19:47 UTC, sonnyp commented on src/Library/demos/User Info/main.js
> +);
can you move this below the `import`s ? (with a newline separation)

it makes it clear that it's related

2023-06-19 19:47 UTC, sonnyp commented on src/Library/demos/User Info/main.js
> +  // call the portal function
```suggestion
```

2023-06-19 19:47 UTC, sonnyp commented on src/Library/demos/User Info/main.js
> +  user_info = user_info.deepUnpack();
I really like the gvariant description comment you made in the other PR, I would do something similar here

```suggestion
  const result = await portal.get_user_information(parent, reason, null, null);
  // result is a ...
  const user_info = user_info.deepUnpack();
```

2023-06-19 19:47 UTC, sonnyp commented on src/Library/demos/User Info/main.js
> +  //update values
this comment isn't helpful IMHO

2023-06-19 19:47 UTC, sonnyp commented on src/Library/demos/User Info/main.js
> +  //post-request updation
ditto

2023-06-19 19:47 UTC, sonnyp commented on src/Library/demos/User Info/main.blp
> +      }
can you use a AdwEntryRow and a "Request" button like ASHPD app?

![image](https://github.com/sonnyp/Workbench/assets/19673/bbf88cf3-3ffd-4a01-b3fa-d82d8c39cab1)

I would drop the question too

2023-06-19 19:47 UTC, sonnyp commented on src/Library/demos/User Info/main.blp
> +    }
Can you do like ASHPD and hide this until we have the information ?

You could use a Revealer for :sunglasses: effect

2023-06-20 08:02 UTC, SoNiC-HeRE commented
## Made the following changes:
- Updated Title to Account
- Used Revealer
- Improved UI
- Refined Code
- Kept the UI and Code minimalistic

```Used Listbox as a child since Gtk.Revealer only supports  one child widget  at a time```

2023-06-20 18:17 UTC, sonnyp approved these changes
Nice

2023-06-20 18:17 UTC, merged