library: add Event Controlles entry
sonnyp/Workbench pull request #356
Opened 2023-06-21 21:04 UTC by halfmexican

closes #266

2023-06-23 16:49 UTC, andyholmes commented
This is great start. How about doing this:

1. Make three `Gtk.Button`s in a box with the `linked` CSS class.
2. Put that box in a `Gtk.Frame` so you have a sort of touchpad looking thing
3. Add the event controller to the frame, and set the `button` property to `0` so it catches any button click.

Then if you setup a handler for `::pressed` and `::released`, you can do this:

```js
gesture_secondary_click.connect("pressed", (gesture, n_press, x, y) => {
  switch (gesture.get_current_button()) {
    case Gdk.BUTTON_PRIMARY:
      primary_button.add_css_class("suggested-action");
      break;

    case Gdk.BUTTON_MIDDLE:
      middle_button.add_css_class("suggested-action");
      break;

    case Gdk.BUTTON_SECONDARY:
      secondary_button.add_css_class("suggested-action");
      break;
  }
});

gesture_secondary_click.connect("released", (gesture, n_press, x, y) => {
  switch (gesture.get_current_button()) {
    case Gdk.BUTTON_PRIMARY:
      primary_button.remove_css_class("suggested-action");
      break;

    case Gdk.BUTTON_MIDDLE:
      middle_button.remove_css_class("suggested-action");
      break;

    case Gdk.BUTTON_SECONDARY:
      secondary_button.remove_css_class("suggested-action");
      break;
  }
});
```

2023-06-29 00:20 UTC, andyholmes requested changes
Looks good, just needs a few UI tweaks and the `Gtk.GestureClick` to be used instead of the button's `::clicked` signal.

2023-06-29 00:20 UTC, andyholmes commented on src/Library/demos/Event Controllers/main.js
> +});
The event controller here is unused, and actually just demonstrating the `Gtk.Button::clicked` signal which uses an event controller internally.

Instead this event controller should be attached to something that usually doesn't respond to clicks, like a `Gtk.Box` with a `Gtk.Label` inside.

2023-06-29 00:20 UTC, andyholmes commented on src/Library/demos/Event Controllers/main.js
> +});
This is a great, simple demonstration of this event controller. The only problem I have is that there's no indication which way you can swipe. Maybe add a simple `Gtk.StackSwitcher` above/below with "Start" and "Finish" labels for the pages?

2023-06-29 00:20 UTC, andyholmes commented on src/Library/demos/Event Controllers/main.blp
> +      label: "EventControllerKey Example";
```suggestion
      label: _("EventControllerKey Example");
```

2023-06-29 00:20 UTC, andyholmes commented on src/Library/demos/Event Controllers/main.blp
> +      label: "GestureClick Example";
```suggestion
      label: _("GestureClick Example");
```

2023-06-29 00:20 UTC, andyholmes commented on src/Library/demos/Event Controllers/main.blp
> +  child: Box {
Instead of using the `margin-*` properties on all the children, you should just use the `spacing` property on this parent box.

2023-06-29 00:20 UTC, andyholmes commented on src/Library/demos/Event Controllers/main.blp
> +      label: "GestureSwipe Example";
```suggestion
      label: _("GestureSwipe Example");
```

2023-06-29 00:20 UTC, andyholmes commented on src/Library/demos/Event Controllers/main.blp
> +        title: "pic1";
These are user-visible strings, so must be marked for translation if set.

2023-07-01 21:43 UTC, andyholmes commented
Is this ready for re-review? If so remember to hit the button, or I will likely overlook it :)

I'll be back with more availability tomorrow, so we can catch up during the meeting.

2023-07-04 00:03 UTC, halfmexican commented
No this is not ready for rereview

2023-07-04 00:22 UTC, halfmexican commented
My apologies, haven't been able to touch this demo as much since the camera entry took so long. Should be good for rereview now

2023-07-04 22:07 UTC, andyholmes requested changes
Looks really good.

Needs some formatting in the Blueprint file, and a few adjustments to the layout, then it's good to go.

2023-07-04 22:07 UTC, andyholmes commented on src/Library/demos/Event Controllers/main.blp
> +      label: _("Ctrl+Click me!");
```suggestion
      label: _("Ctrl + Click to Activate");
```

2023-07-05 16:20 UTC, halfmexican commented
I think it did correctly, I've given each section a box and then surrounded those boxes with another box with a spacing of 18

2023-07-05 19:41 UTC, andyholmes approved these changes
Looks great!

I added a `GtkFrame` around the `GtkStack`, because it looked like it was sort of floating.

2023-07-05 19:41 UTC, merged