library: Add Actionbar entry
sonnyp/Workbench pull request #376
Opened 2023-07-01 20:24 UTC by SoNiC-HeRE

Kept the entry minimalistic so as to create UI as shown in the documentation:

![image](https://github.com/sonnyp/Workbench/assets/96797205/49908ab4-9466-4bd5-bf5a-843cbcd3769b)

2023-07-02 11:33 UTC, sonnyp requested changes
> Kept the entry minimalistic so as to create UI as shown in the documentation:

It doesn't appear to be the case.

And the layout is broken

[Screencast from 2023-07-02 13-26-20.webm](https://github.com/sonnyp/Workbench/assets/19673/dd0102ec-706c-4b40-8357-428f16b13fd3)


From https://docs.gtk.org/gtk4/class.ActionBar.html

> It is expected to be displayed below the content and expand horizontally to fill the area.

I think a better demo would be some kind of fake window (just a box with `card` style class) of 720x360 pixels with the action bar at the bottom

2023-07-02 11:33 UTC, sonnyp commented on src/Library/demos/Action Bar/main.js
> +box.append(buttonsBox);
I don't see why all of this isn't part of the Blueprint

2023-07-02 11:33 UTC, sonnyp commented on src/Library/demos/Action Bar/main.json
> +  "panels": ["code", "preview"],
```suggestion
  "panels": ["ui", "preview"],
```

2023-07-02 11:33 UTC, sonnyp commented on src/Library/demos/Action Bar/main.blp
> +      revealed: false;
let's show it by default and have a toggle for this

2023-07-02 15:31 UTC, SoNiC-HeRE commented
Okay, I'll make the required changes

2023-07-04 09:51 UTC, SoNiC-HeRE commented
> > Kept the entry minimalistic so as to create UI as shown in the documentation:
> 
> It doesn't appear to be the case.
> 
> And the layout is broken
> Screencast.from.2023-07-02.13-26-20.webm
> 
> From https://docs.gtk.org/gtk4/class.ActionBar.html
> 
> > It is expected to be displayed below the content and expand horizontally to fill the area.
> 
> I think a better demo would be some kind of fake window (just a box with `card` style class) of 720x360 pixels with the action bar at the bottom
> 
> The fake window could have a status page with a button to toggle reveal on and off

Is this what you meant?

2023-07-04 14:09 UTC, sonnyp commented
@SoNiC-HeRE yes but not as a window

If we can avoid it we should at it puts the demo behind a button

2023-07-04 14:09 UTC, sonnyp commented
Also I meant 720h and 360w - like a phone

2023-07-05 15:39 UTC, sonnyp reviewed
Good start.

The action bar should be visible by default so the user doesn't have to click a button to see what it is. Since the bar will be revealed by default, no need for it to be primary action.

> with a button to toggle reveal on and off

The button doesn't toggle on and off. You can make it a "Reveal" ToggleButton.

The chosen icon buttons aren't great. Since this is for contextual actions, we should use icons that are call to actions.

What about `call-start-symbolic` on the left and `padlock2-symbolic` on the right?

For the center a dropdown is fine but it's too long, can you use emojis for the strings ?

2023-07-05 15:39 UTC, sonnyp commented on src/Library/demos/Action Bar/main.blp
> +  width-request: 36;
?

```suggestion
  height-request: 720;
  width-request: 360;
```

2023-07-05 15:39 UTC, sonnyp commented on src/Library/demos/Action Bar/main.blp
> +    title: "Action Bar";
please try to remember

```suggestion

  Adw.StatusPage {
    title: _("Action Bar");
```

2023-07-05 15:39 UTC, sonnyp commented on src/Library/demos/Action Bar/main.blp
> +    description: _("ActionBar is designed to present contextual actions.");
We shouldn't repeat the title in the description

```suggestion
    description: _("Toolbar for contextual actions.");
```

2023-07-06 12:55 UTC, sonnyp approved these changes
thanks

couple of small fixes https://github.com/sonnyp/Workbench/pull/376/commits/7d1fa76e2f48384d50033dc68e6ea3147e3cb98a

2023-07-06 12:55 UTC, merged

2023-07-07 12:54 UTC, SoNiC-HeRE commented
Closes #379