library: Add Scrolled Window entry
sonnyp/Workbench pull request #434
Opened 2023-07-19 05:01 UTC by AkshayWarrier

Closes #419
There is an edge case where if the Start/End buttons are pressed when it's already at the edge, the buttons get disabled for the animation duration. Is that problematic and if so, what might be the simplest way to handle it.

2023-08-06 22:28 UTC, sonnyp requested changes
Great demo :+1: 

Sorry for taking so long to review.

> Is that problematic and if so, what might be the simplest way to handle it?

When the button is pressed, you can simply check if the scrolled area is already at the edge and do nothing.

I think an even better solution is to disable the corresponding start or end button when it's already at the edge.

start edge is adj value = adj lower
end endge is adj value = adj upper

Also please reduce animation duration to 1 sec, it's a bit too slow now.

2023-08-07 05:05 UTC, AkshayWarrier commented
> start edge is adj value = adj lower
> end endge is adj value = adj upper

I can't really do this because weirdly enough this is not true, I tried logging adj.upper and adj.value when the scrollbar is at the end edge and I got upper = 3360 and value = 2782. I'm not sure what adj.upper is then, but the scrollbar probably just stops scrolling after 2782. And the scrollbar doesn't have property to let me know whats the actual maximum distance it can scroll.

2023-08-07 05:13 UTC, AkshayWarrier commented
Though in my opinion, I think it's fine the way it is because I'm already reducing the animation speed to 1s so the buttons are not disabled that long, and most people looking for a Scrolled Window demo probably are only looking for the UI/Blueprint and the demo shows how to programmatically scroll if necessary. I'm concerned adding extra logic to decide when the buttons are enabled/disabled is very specific to the demo?

2023-08-07 11:46 UTC, sonnyp commented
> I can't really do this because weirdly enough this is not true, I tried logging adj.upper and adj.value when the scrollbar is at the end edge and I got upper = 3360 and value = 2782. I'm not sure what adj.upper is then, but the scrollbar probably just stops scrolling after 2782. And the scrollbar doesn't have property to let me know whats the actual maximum distance it can scroll.

Right, you need to do some simple maths to get positions relative to each others.

Something like
upper - page-size = value
2240 - 598 = 1642

> The [GtkAdjustment:value](https://docs.gtk.org/gtk4/property.Adjustment.value.html) field sets the position of the thumb and must be between [GtkAdjustment:lower](https://docs.gtk.org/gtk4/property.Adjustment.lower.html) and [GtkAdjustment:upper](https://docs.gtk.org/gtk4/property.Adjustment.upper.html) - [GtkAdjustment:page-size](https://docs.gtk.org/gtk4/property.Adjustment.page-size.html). The [GtkAdjustment:page-size](https://docs.gtk.org/gtk4/property.Adjustment.page-size.html) represents the size of the visible scrollable area.

See https://docs.gtk.org/gtk4/class.Scrollbar.html

>. most people looking for a Scrolled Window demo probably are only looking for the UI/Blueprint

Maybe but the complexity here is in `Code`.

>  I'm concerned adding extra logic to decide when the buttons are enabled/disabled is very specific to the demo?

It's good to keep demos simple but knowing if the scroll is at the edge or not is something very common. Specially when you have a "scroll to top" button like on timelines that you want to hide or disable when you're already at the top.

I think it's worth our time.

2023-08-09 20:57 UTC, sonnyp requested changes
Almost, the start / end buttons should only be disabled if at the edge.

For that you should listen to the property `value` on the adjustment. Not sure what's best between the signals `value-changed` and `notify::value`. Would be curious to know the difference if you can figure it out.

2023-08-09 20:57 UTC, sonnyp commented on src/Library/demos/Scrolled Window/main.js
> +let orientation = 0;
Why do we need this if there is already `container.orientation` ?

```
const scrollbars = {
  [Gtk.Orientation.HORIZONTAL]: scrolled_window.get_hscrollbar(),
  [Gtk.Orientation.VERTICAL]: scrolled_window.get_vscrollbar(),
}
```

2023-08-11 13:03 UTC, sonnyp approved these changes
Nice :+1: !

Did you figure out the difference between `notify::value` and `value-changed` ?

2023-08-11 13:03 UTC, merged

2023-08-11 16:48 UTC, AkshayWarrier commented
Ah not really, I just ended up using ``value-changed`` since ``Gtk.Adjustment`` already provides that signal.