library: Add vala demo for Button
sonnyp/Workbench pull request #447
Opened 2023-07-26 16:09 UTC by SpikedPaladin

Adds Vala code demo for Button

2023-07-26 19:24 UTC, lw64 requested changes
Thanks! Looks good.

2023-07-26 19:24 UTC, lw64 commented on src/Library/demos/Button/main.vala
> +  foreach (var id in button_ids) {
Use string instead of var here please.

2023-07-27 15:02 UTC, SpikedPaladin commented on src/Library/demos/Button/main.vala
> +  foreach (var id in button_ids) {
Fixed

2023-07-31 15:59 UTC, sonnyp approved these changes

2023-07-31 15:59 UTC, merged