Manuals: Optimize loading docs
sonnyp/Workbench pull request #573
Opened 2023-09-05 08:56 UTC by AkshayWarrier

2023-09-11 15:42 UTC, AkshayWarrier commented on src/DocumentationViewer.js
> +  );
I haven't measured the times but there's a noticeable performance difference. When opening Manuals, you can still see the items in the sidebar coming in with ``for await`` but when reading 10 files at a time it's almost instant.

2023-09-11 18:57 UTC, andyholmes commented on src/DocumentationViewer.js
> +  );
Yeah, I think the default `async` iterator is usually the better choice, but for a load-time operation like this it ends up deferring too much.

2023-09-11 19:22 UTC, andyholmes requested changes
Looks pretty good, just a few tweaks.

2023-09-11 19:22 UTC, andyholmes commented on src/DocumentationViewer.js
> +      logError(error);
Maybe in context, this should re-`throw` the error instead? I'm not sure what the best behaviour is if something actually goes wrong.

2023-09-11 19:22 UTC, andyholmes commented on src/DocumentationViewer.js
> +    "standard::*",
```suggestion
    "standard::name,standard::type",
```

Since we're here to optimize.

2023-09-11 19:22 UTC, andyholmes commented on src/DocumentationViewer.js
> +    browse_list_view.model = createBrowseSelectionModel(root_model, webview);
```suggestion
    try {
      const root_model = Gio.ListStore.new(DocumentationPage);

      scanLibraries(root_model, base_path)
        .then(() => {
          browse_list_view.model.selected = 12;
          const search_model = flattenModel(root_model);
          filter_model.model = search_model;
        })
        .catch(console.error);

      browse_list_view.model = createBrowseSelectionModel(root_model, webview);
    } catch(error) {
      console.error(error);
    }
```

I don't know where it makes most sense to `catch`, but there should either be a `try..catch` here or a `catch()` when it's invoked.

2023-09-12 06:27 UTC, AkshayWarrier commented
I made the changes and I also realized that ``StringSorter`` wasn't working in the browse model so I switched back to using ``CustomSorter``

2023-09-12 20:47 UTC, andyholmes approved these changes
LGTM

2023-09-12 20:47 UTC, merged