library: Port Actions demo to Python
sonnyp/Workbench pull request #705
Opened 2023-10-27 06:32 UTC by rolandlo

This PR ports the Actions demo to Python

I have tried to stay as close as possible to the JS code. Not sure if I should have avoided using lambdas as in the Welcome demo, see [comment](https://github.com/sonnyp/Workbench/pull/570/files#r1372677674). I used lambdas because here it's only for a single statement, whereas in the Welcome demo there were two statements.

The `open_uri` actions somehow don't work yet. Is this something that needs to be fixed on the "core" side or is there something wrong with my code?

2023-10-27 09:37 UTC, Hofer-Julian commented
>  I used lambdas because here it's only for a single statement

If it's only a single statement, it's fine to use lambdas IMO

2023-10-27 10:09 UTC, rolandlo commented
> @rolandlo thanks! please consider adding yourself to the list of contributors in `about.js`
Done!

2023-10-28 16:23 UTC, theCapypara requested changes
Thanks! In general this looks good and works perfectly, however could you make sure your code is formatted to follow [PEP 8](https://peps.python.org/pep-0008/) and uses 4 spaces for indentation? 

You can use `pycodestyle` to verify. You can ignore error `E402 module level import not at top of file`, since that isn't possible due to the `require_version`.

Also we may want to change the demo's blueprint file to also link to the PyGObject docs (or remove the GJS link), what do you think @sonnyp?

2023-10-28 16:23 UTC, theCapypara commented on src/Library/demos/Actions/main.py
> +  name = "open-bookmarks",
One example for PEP 8 is that there should be no spaces around the `=` in keyword arguments.

2023-10-28 17:37 UTC, rolandlo commented
> Thanks! In general this looks good and works perfectly, however could you make sure your code is formatted to follow [PEP 8](https://peps.python.org/pep-0008/) and uses 4 spaces for indentation?
> 
> You can use `pycodestyle` to verify. You can ignore error `E402 module level import not at top of file`, since that isn't possible due to the `require_version`.
> 

Done! It would be good to add these style requirements to the [style guide](https://github.com/sonnyp/Workbench/wiki/Style-Guide), so everybody can learn about them without going through previous PR's.

> Also we may want to change the demo's blueprint file to also link to the PyGObject docs (or remove the GJS link), what do you think @sonnyp?

I have added a commit adding that link. Let me know if I should remove the commit (or make changes to it).

Back to:

> The `open_uri` actions somehow don't work yet. Is this something that needs to be fixed on the "core" side or is there something wrong with my code?

Is it only for me that the Linkbuttons from the bookmarks don't work (the links are not opened) with the Python code and the Actions Documentation section is disabled?
![grafik](https://github.com/sonnyp/Workbench/assets/40485433/a67068a6-a38b-4ffe-9fbd-43984569df46)

2023-10-28 17:54 UTC, theCapypara commented
Oh, that's very odd, I somehow didn't even notice that the first time around. 
Must be an issue in PyGObject, somehow? It's really odd since there's no code in either the JS/Python demo related to that, but I can't really imagine how the language bindings would break this.

![grafik](https://github.com/sonnyp/Workbench/assets/3512122/a47fa04e-eff3-436c-81a2-a3efe8274f63)

However looking at the inspector it seems the "sensitive" property for the generated ModelButtons is somehow filled with the label...

2023-10-28 17:58 UTC, theCapypara commented
Oh wow, wait, disregard my previous comment even though I double and tripple checked before sending (and was very confused how this is even possible) I just was off by one line. That is the text.

2023-10-29 10:43 UTC, theCapypara commented
Okay this is not a bug in PyGObject, this is a general issue with the way the external previewers work at the moment: https://github.com/sonnyp/Workbench/issues/715

2023-10-29 10:46 UTC, theCapypara approved these changes

2023-10-29 10:48 UTC, rolandlo commented
Should I squash all the commits (or at least the first two commits) into one?

2023-10-29 11:23 UTC, theCapypara commented
IMO we could still merge this. There are already some other demos broken right now because of #715 / #110

2023-10-29 11:25 UTC, rolandlo commented
Ok then, let's squash and merge.

2023-10-29 11:36 UTC, merged