Library: Port 'CSS Gradients' to Python
sonnyp/Workbench pull request #724
Opened 2023-10-29 19:18 UTC by UrtsiSantsi

Marking as draft, since it doesn't work for me - see #713

2023-10-30 10:30 UTC, theCapypara commented
I'm not sure I understand, your commit passed CI. Black expects a new line at the end and your file has one.

2023-10-30 10:35 UTC, theCapypara requested changes
There really seems to be something wrong with importing SourceView, I can reproduce this in your example. It might be that we need to make sure GtkSource is loaded in the previewer too, since it's defined in the Builder XML, I did not check that yet. Will have a look.

2023-10-30 10:35 UTC, theCapypara commented on src/Library/demos/CSS Gradients/main.py
> +def generateCss():
Please use snake case names (`generate_css`)

2023-10-30 10:35 UTC, theCapypara commented on src/Library/demos/CSS Gradients/main.py
> +        css = """
This (and the others) are not valid format strings. You want something like:
```py
f""""
{angle_string}deg
""""
```

2023-10-30 16:20 UTC, gregorni commented
@UrtsiSantsi Is there any way I can contact you outside GitHub? We're both working on Python demos right now, in parallel, so I thought it would be smart if we talked together to make sure we don't accidentally port the same demo.

If you're on Matrix, you can find me under https://matrix.to/#/@gregorni:gnome.org

2023-10-31 12:44 UTC, theCapypara commented
I'll add the Adw and other initialization code to the previewer as well, but please also keep it in the demo, that's good to have for people that try to copy the demos into their own apps.

2023-10-31 12:59 UTC, theCapypara approved these changes

2023-10-31 13:07 UTC, merged